name: MonoRepo CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        node-version: [16, 18, 20]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Building monorepos
        run: yarn build
